## Advance Operation with Business examples

In [6]:
import numpy as np
import matplotlib as plt

## Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

In [21]:
sales_data = np.array([
    [1, 150000, 180000, 120000, 250000], 
    [2, 160000, 200000, 240000, 260000],
    [3, 180000, 190000, 230000, 270000],
    [4, 170000, 210000, 250000, 290000],
    [5, 190000, 220000, 250000, 280000],
])

print("Top three restaurant data: \n", sales_data[:, 1:])

Top three restaurant data: 
 [[150000 180000 120000 250000]
 [160000 200000 240000 260000]
 [180000 190000 230000 270000]
 [170000 210000 250000 290000]
 [190000 220000 250000 280000]]


In [35]:
# total sales per year
year_total = np.sum(sales_data[:, 1:], axis=0)
sums = np.sum(year_total[:])
print(year_total)
print("All company revenu sum: ",sums)


min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

max_sales = np.max(sales_data[:, 1:], axis=1)
print(max_sales)

avrage_sales = np.mean(sales_data[:, 1:], axis=1)
print(avrage_sales)

cumsum = np.cumsum(sales_data[:, 1:], axis=1)
print(f"\n{cumsum}")

[ 850000 1000000 1090000 1350000]
All company revenu sum:  4290000
[120000 160000 180000 170000 190000]
[250000 260000 270000 290000 280000]
[175000. 215000. 217500. 230000. 235000.]

[[150000 330000 450000 700000]
 [160000 360000 600000 860000]
 [180000 370000 600000 870000]
 [170000 380000 630000 920000]
 [190000 410000 660000 940000]]


## Which time use axis 0 and 1

From top to bottom use axis 0
From left to right use axis 1

## Vectors

In [40]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print("Addition", vector1 + vector2)
print("Multiplication", vector1 * vector2)
print("Dot product", np.dot(vector1, vector2))

Addition [ 7  9 11 13 15]
Multiplication [ 6 14 24 36 50]
Dot product 130


In [41]:
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger'])
vecorize_upper = np.vectorize(str.upper)
print(vecorize_upper(restaurant_types))

['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER']


In [44]:
monthly_avg = sales_data[:, 1:] / 12

print(np.round(monthly_avg)) # it will return monthly avrage for per year

[[12500. 15000. 10000. 20833.]
 [13333. 16667. 20000. 21667.]
 [15000. 15833. 19167. 22500.]
 [14167. 17500. 20833. 24167.]
 [15833. 18333. 20833. 23333.]]
