## Numpy Array Operations

In [9]:
import numpy as np

In [13]:
arr = np.arange(11)
print(arr)
print(arr[0:10])
print(arr[0:10:2])
print(arr[-4])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
7


In [15]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],

])
print("first row second coloum", arr_2d[1, 2])
print("Traget row",arr_2d[1])
print("Traget coloum",arr_2d[:, 1])

first row second coloum 6
Traget row [4 5 6]
Traget coloum [2 5 8]


## Sorting

In [16]:
unsorted  = np.array([8, 5, 4, 7 , 6, 9, 2, 3, 1])
print(np.sort(unsorted))

arr_2d = np.array([[3, 1], [1, 2], [2, 3]])
print(np.sort(arr_2d, axis= 0))

[1 2 3 4 5 6 7 8 9]
[[1 1]
 [2 2]
 [3 3]]


## Filter

In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even =  numbers[numbers % 2 == 0]
print(even)

[ 2  4  6  8 10]


## Filter with mask

In [18]:
mask = numbers > 5
print("Number greater than 5: ", numbers[mask])

Number greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.Where()

In [19]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(numbers[where_result])

[1 3 5]
[ 6  7  8  9 10]


In [24]:
condition_array = np.where(numbers > 5, "true", "false") # where same work like arry but mostly we use it for specific conditions.
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [23]:
if(condition_array):
    print(numbers * 4)

[ 4  8 12 16 20 24 28 32 36 40]


## Adding and Removing Data

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combine_arr = np.concatenate((arr1, arr2))

print(combine_arr)

[1 2 3 4 5 6]


## Array Compatibilty

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Compatibilty Shape: ", a.shape == b.shape)

Compatibilty Shape:  True


## Adding New Row

In [45]:
original = np.array([[1, 2], [3, 4], ])
new_row = np.array([[5, 6]])

add_new_row = np.vstack((original, new_row))

print(add_new_row)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
org  = np.array([[1, 2], [3, 4]])
new_row = np.array([[5], [6]])
result = np.hstack((org, new_row))
print(result)

[[1 2 5]
 [3 4 6]]


## Deleting row and coloum

In [49]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(deleted)


[1 2 4 5]
