## Numpy Array and Basics

In [2]:
import numpy as np 

## Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4])
print("arr_1d: ", arr_1d)

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("arr_2d: ", arr_2d)

arr_1d:  [1 2 3 4]
arr_2d:  [[1 2 3 4]
 [5 6 7 8]]


## List vs numpy

In [8]:
py_list = [1, 2, 3]
print("Python list multi", py_list * 2)

numpy_array = np.array([1, 2, 3])
print("numpy array multi", numpy_array * 2)


import time

start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n list operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2 
print("\n Numpy operation time: ", time.time() - start)

Python list multi [1, 2, 3, 1, 2, 3]
numpy array multi [2 4 6]

 list operation time:  0.1577761173248291

 Numpy operation time:  0.009982585906982422


## Creating array from scrach

In [16]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Onse array: \n", ones)

full = np.full((2, 3), 4)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", np.round(random))

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Onse array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[4 4 4]
 [4 4 4]]
random array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [17]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DataType", arr.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
DataType int64


## Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped: ", reshaped)

flattened = reshaped.flatten()
print("Flatten: ",flattened)

# revel (return view, instead of copy)
reveled = reshaped.ravel()
print("Reveled: ", reveled)

transpose = reshaped.T
print("Transpose: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
