In [1]:
import numpy as np

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.random.rand(2, 2)
arr3 = np.ones((2, 2))

In [7]:
np.save('array1.npy', arr1)
np.save('array2.npy', arr2)
np.save('array3.npy', arr3)

In [10]:
load_data1 = np.load('array1.npy')
load_data2 = np.load('array2.npy')
load_data3 = np.load('array3.npy')

print(load_data1)
print(load_data2)
print(load_data3)

[[1 2 3]
 [4 5 6]]
[[0.28275594 0.6359768 ]
 [0.59921372 0.63159141]]
[[1. 1.]
 [1. 1.]]
