## Numpy Array Operations

In [3]:
import numpy as np

In [8]:
arr = np.arange(11)
print(arr)
print(arr[0:10])
print(arr[0:10:2])
print(arr[-4])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
7


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],

])
print("first row second coloum", arr_2d[1, 2])
print("Traget row",arr_2d[1])
print("Traget coloum",arr_2d[:, 1])

6
Traget row [4 5 6]
Traget coloum [2 5 8]
